### ISSUE TITLE
Add information about licensing

### ISSUE THREAD

**Issue by vbauer** [lawloretienne/TinderStack#4]

**Comment by lawloretienne** [comment]
@vbauer Why do i need licensing?

**Comment by vbauer** [comment]
I'm not sure that you need it, but it is just a typically question after submission project on Android Arsenal (https://android-arsenal.com/details/3/4946)

.. so I usually suggest authors of projects to add it :) Developers would like to know how could they use source code

**Comment by lawloretienne** [comment]
Ya this isn't necessarily a library, just a sample repo I created.

**Comment by lawloretienne** [comment]
Oh i didnt even realize it was up there.

**Comment by lawloretienne** [comment]
I just added a LICENSE
