### ISSUE TITLE
Listener for swipe left or right action

### ISSUE THREAD

**Issue by mladenbabic** [lawloretienne/TinderStack#6]
I would like to implement this nice lib in my app, but I can not find an example how to receive swipe left or right event in an activity/fragment. Any example about it would be a great help.

Thanx

**Comment by lawloretienne** [comment]
Are you referring to the Event Bus. I have a class called RxBus that publishes events. Maybe that is what you are looking for.

**Comment by mladenbabic** [comment]
OK, tnx.  I found only TopCardMovedEvent class. It would be more helpful if we have also f.e. CardMovedLeftEvent or CardMovedRightEvent classes. Anyway, I'll create them in my project.
Tnx  a lot.
